name: tests

on:
  push:
  pull_request:

jobs:
  unittest:
    runs-on: ubuntu-latest

    steps:
      - name: Получить код
        uses: actions/checkout@v4

      - name: Установить Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Запустить тесты
        run: python -m unittest discover -s tests -v
